---
title: "4893_Final"
output: html_document
date: "2024-03-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)

batting <- read.csv("/Users/justincarter/Downloads/Batting.csv")
HOF <-  read.csv("/Users/justincarter/Downloads/HallOfFame.csv")
fielding <- read.csv("/Users/justincarter/Downloads/Fielding.csv")
HOF <-  read.csv("/Users/justincarter/Downloads/HallOfFame.csv")

batting <- batting[1:79248,]
batting <- batting %>% replace(is.na(.), 0)
batting <- batting %>% summarize(G = sum(G), R = sum(R), H = sum(H), XBH = sum(X2B)+sum(X3B),
                                          HR = sum(HR), RBI = sum(RBI), SB = sum(SB), SO = sum(SO),
                                          Ryear = max(yearID), .by = "playerID")

fielding <- filter(fielding, POS != "P")
fielding <- fielding %>% replace(is.na(.), 0)
fielding <- fielding  %>% summarize(PO = sum(PO), A = sum(A), E = sum(E), .by = "playerID" )

position_players <- inner_join(batting, fielding, by = "playerID")
position_players$HOF <- 0

HOF <- filter(HOF, inducted == "Y" & category == "Player")
HOF <- semi_join(HOF, position_players, by = "playerID")
HOF <- HOF  %>% arrange(HOF, playerID)

HOF_players <- semi_join(position_players, HOF, by = "playerID")
HOF_players <- HOF_players  %>% arrange(HOF_players, playerID)
HOF_players$HOF = 1
HOF_players$years_to_induction <- (c(HOF$yearid) - c(HOF_players$Ryear))
non_HOF_Players <- anti_join(position_players, HOF, by = "playerID")
position_players <- full_join(HOF_players, non_HOF_Players)

position_players$HOF <- as.factor(position_players$HOF)
```


```{r}
HOF <-  read.csv("/Users/justincarter/Downloads/HallOfFame.csv")
pitching <- read.csv("/Users/justincarter/Downloads/Pitching.csv")

pitching <- pitching[1:32898,]
pitching <- pitching  %>% replace(is.na(.), 0)
pitching <- pitching %>% summarize(G = sum(G), W = sum(W), L = sum(L),
                                   WHIP = ((sum(H) + sum(BB)) / (sum(IPouts) * 3)),
                                   ERA = (sum(ER) / (sum(IPouts) / 3)) * 9, 
                                   SO = sum(SO), BB = sum(BB), HR = sum(HR), Ryear = max(yearID),
                                   .by = "playerID")
pitching['ERA'][sapply(pitching['ERA'], is.infinite)] <- 10
pitching['ERA'][sapply(pitching['ERA'], is.nan)] <- 10
pitching['WHIP'][sapply(pitching['WHIP'], is.infinite)] <- 2
pitching['WHIP'][sapply(pitching['WHIP'], is.nan)] <- 2

HOF <- filter(HOF, inducted == "Y" & category == "Player")
HOF <- semi_join(HOF, pitching, by = "playerID")
HOF <- HOF  %>% arrange(HOF, playerID)

HOF_pitchers <- semi_join(pitching, HOF, by = "playerID")
HOF_pitchers <- HOF_pitchers  %>% arrange(HOF_pitchers, playerID)
HOF_pitchers$HOF = 1
HOF_pitchers$years_to_induction <- (c(HOF$yearid) - c(HOF_pitchers$Ryear))
HOF_pitchers <- filter(HOF_pitchers, G>100)
non_HOF_pitchers<- anti_join(pitching, HOF, by = "playerID")
non_HOF_pitchers$HOF = 0
pitchers <- full_join(HOF_pitchers, non_HOF_pitchers)
pitchers$HOF <- as.factor(pitchers$HOF)
```
```{r}
library(caTools) 
library(randomForest)
library(caret)

set.seed(2002)

tuned_1 <- tuneRF(x = position_players[,c(2,3,4,5,6,7,8,9,11,12,13)], y = position_players[,14],
                  ntreeTry = 500, stepFactor = 1.5, improve = 1e-5 )

tuned_2 <- tuneRF(x = pitchers[,c(2,3,4,5,6,7,8,9)], y = pitchers[,11],
                  ntreeTry = 500, stepFactor = 1.5, improve = 1e-5 )

tuned_3 <- tuneRF(x = HOF_players[,c(2,3,4,5,6,7,8,9,11,12,13)], y = HOF_players[,15],
                  ntreeTry = 500, stepFactor = 1.5, improve = 1e-5 )

tuned_4 <- tuneRF(x = HOF_pitchers[,c(2,3,4,5,6,7,8,9)], y = HOF_pitchers[,12],
                  ntreeTry = 500, stepFactor = 1.5, improve = 1e-5 )
```

```{r}
set.seed(2002)

data_split <- sample.split(position_players$G, SplitRatio = 0.75 )

train_1 <- filter(position_players, data_split == TRUE)
test_1 <- filter(position_players, data_split == FALSE)
train_1 <-  as.data.frame(train_1)
test_1 <- as.data.frame(test_1)

RF_pPlayer <- randomForest(x = train_1[,c(2,3,4,5,6,7,8,9,11,12,13)], y = train_1[,14],
                           mtry = 4, ntree = 500)
plot(RF_pPlayer)
RF_pPlayer
predictions_1 <- predict(RF_pPlayer, newdata = test_1[,c(2,3,4,5,6,7,8,9,11,12,13)])
tab_1 <- confusionMatrix(data = predictions_1, reference = test_1[,14])
tab_1
varImpPlot(RF_pPlayer, main = "Importance")
importance(RF_pPlayer)
```

```{r}
set.seed(2002)
data_split_2 <- sample.split(HOF_players$playerID, SplitRatio = 0.75 )

train_2 <- filter(HOF_players, data_split_2 == TRUE)
test_2 <- filter(HOF_players, data_split_2 == FALSE)
train_2 <-  as.data.frame(train_2)
test_2 <- as.data.frame(test_2)

RF_HOF_Pplayers <- randomForest(formula = years_to_induction ~ G + R + H + XBH + HR + RBI + SB
                   + SO + PO + E + A, data = train_2, mtry = 2,  ntree = 500)
plot(RF_HOF_Pplayers)
RF_HOF_Pplayers
varImpPlot(RF_HOF_Pplayers, main = "Importance")
importance(RF_HOF_Pplayers)
```

```{r}
set.seed(2002)
data_split_3 <- sample.split(pitchers$playerID, SplitRatio = 0.75 )

train_3 <- filter(pitchers, data_split_3 == TRUE)
test_3<- filter(pitchers, data_split_3 == FALSE)
train_3 <-  as.data.frame(train_3)
test_3 <- as.data.frame(test_3)

RF_pitchers <- randomForest(x = train_3[,c(2,3,4,5,6,7,8,9)], y = train_3[,11],
                            mtry = 4, ntree = 500)
plot(RF_pitchers)
RF_pitchers
predictions_2 <- predict(RF_pitchers, newdata = test_3[,c(2,3,4,5,6,7,8,9)])
tab_2 <- confusionMatrix(data = predictions_2, reference = test_3[,11])
tab_2
varImpPlot(RF_pitchers, main = "Importance")
importance(RF_pitchers)
```
```{r}
set.seed(2002)
data_split_4 <- sample.split(HOF_pitchers$playerID, SplitRatio = 0.75 )

train_4 <- filter(HOF_pitchers, data_split_4 == TRUE)
test_4 <- filter(HOF_pitchers, data_split_4 == FALSE)
train_4 <-  as.data.frame(train_4)
test_4 <- as.data.frame(test_4)

RF_HOF_pitchers <- randomForest(formula = years_to_induction ~ G + W + L + WHIP + 
                                  ERA + SO + BB + HR, data = HOF_pitchers, mtry = 2,  ntree = 500)
plot(RF_HOF_pitchers)
RF_HOF_pitchers
varImpPlot(RF_HOF_pitchers, main = "Importance")
importance(RF_HOF_pitchers)
```
```{r}
log_Pplayers <- glm(HOF ~ G + R + H + XBH + HR + RBI + SB
                   + SO + PO + E + A, data = train_1, family = "binomial")
summary(log_Pplayers)

predictions_3 <- rep(0, length(test_1[,1]))
probs_1 <- predict(log_Pplayers, newdata = test_1[,c(2,3,4,5,6,7,8,9,11,12,13)], type = "response")
predictions_3[probs_1 > 0.5] <- 1
predictions_3 <- as.factor(predictions_3)
tab_3 <- confusionMatrix(data = predictions_3, reference = test_1[,14])
tab_3
```
```{r}
lm_HOF_Pplayers <- lm(years_to_induction ~ G + R + H + XBH + HR + RBI + SB
                   + SO + PO + E + A, data = train_2)
summary(lm_HOF_Pplayers)
```

```{r}
log_pitchers <- glm(HOF ~ G + W + L + WHIP + ERA + SO + BB + HR, data = train_3,
                    family = "binomial")
summary(log_pitchers)

predictions_4 <- rep(0, length(test_3[,1]))
probs_2 <- predict(log_pitchers, newdata = test_3[,c(2,3,4,5,6,7,8,9)])
predictions_4[probs_2 > 0.5] <- 1
predictions_4 <- as.factor(predictions_4)
tab_4 <- confusionMatrix(data = predictions_4, reference = test_3[,11])
tab_4
```
```{r}
lm_HOF_pitchers <- lm(years_to_induction~ G + W + L + WHIP + ERA + SO + BB + HR,
                      data = train_4,)
summary(lm_HOF_pitchers)
```




